### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by bjones1** [pyinstaller/hooksample#1]
I've pushed changes with general clean-up and fixing of the repo. Some thoughts and questions:

- I'd suggest deleting `make.bat` and `Makefile`. The instructions for building the docs are given in the docs, and this might confuse users who think it will build the frozen executable.
- @htgoebel, do you have any objection to using `default_role = "any"` (see [default_role](http://sphinx-doc.org/config.html#confval-default_role), [:any:](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-any))? This will allow us to remove the unnecessary `:doc:`, `:ref:`, etc. syntax in the docs. I ask since you removed these in your revisions.
- I'm a fan of using [Black](https://black.readthedocs.io/en/stable/index.html) to enforce style. What do you think about running it on this repo?

**Comment by Legorooj** [comment]
@bjones1 @htgoebel 
>I'm a fan of using Black to enforce style. What do you think about running it on this repo?

Black sounds good.

>I'd suggest deleting make.bat and Makefile. The instructions for building the docs are given in the docs, and this might confuse users who think it will build the frozen executable.

Also sounds good. Shall I?

**Comment by bjones1** [comment]
That would be great -- go for it.

**Comment by Temerold** [comment]
Sounds good! :+1:
